/**
 * Jenkins pipeline for Build and Test of Android SDK.
 */

pipeline {
    agent { label 'base-lp-agent'}
    stages {
        stage("Build and Test the SDK") {
            steps {
                timestamps {
                    ansiColor('xterm') {
                        buildAndTest()
                    }
                }
            }
        }
    }
}

def buildAndTest() {
    def buildImage = docker.build(env.JOB_NAME, "./jenkins/build.dockerfile")

    buildImage.inside {
        sh 'make sdk'
    }
}
